version: '3'
services:
  movies-postgres:
    container_name: movies-postgres
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    volumes: 
      - /postgresql/data:/var/lib/postgresql/data
    env_file:
      - docker-compose-db.env

  movies_admin:
    container_name: movies_admin
    build:
      context: .
      dockerfile: Dockerfile
    command:  gunicorn config.wsgi:application --bind 0.0.0.0:8000 # python manage.py runserver 0.0.0.0:8000 
    restart: always
    ports:
      - 8000:8000
    env_file: 
      - .env
    volumes:
      - static_volume:/code/config/staticfiles
    depends_on:
      - movies-postgres

  nginx:
    container_name: movies_nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/code/staticfiles
    restart: always
    ports:
      - 80:80
    depends_on:
      - movies_admin
volumes:
  static_volume: