# Generated by Django 3.1 on 2022-10-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='title',
            new_name='sandwich',
        ),
    ]
