# Generated by Django 3.1 on 2022-10-23 12:19

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221023_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 23, 12, 18, 21, 27758, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 10, 23, 12, 18, 21, 27776, tzinfo=utc))),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='full_name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth_date')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': '"content"."person"',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='filmwork',
            options={'ordering': ['-rating'], 'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='created',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='sandwich',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='created',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='modified',
        ),
        migrations.AddField(
            model_name='filmwork',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 12, 18, 21, 27758, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='file_paht',
            field=models.FileField(blank=True, null=True, upload_to='film_works/', verbose_name='file'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='title',
            field=models.CharField(default='default title', max_length=250, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmwork',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 12, 18, 21, 27776, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 12, 18, 21, 27758, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 12, 18, 21, 27776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('tv_show', 'TV show')], default='movie', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='title'),
        ),
        migrations.AlterModelTable(
            name='filmwork',
            table='"content"."film_work"',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='"content"."genre"',
        ),
        migrations.CreateModel(
            name='PersonFilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('actor', 'actor'), ('writer', 'writer'), ('director', 'director')], max_length=50, verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(db_column='film_work_id', on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, related_name='films', to='movies.person')),
            ],
            options={
                'verbose_name': 'Connection Film to Person',
                'verbose_name_plural': 'Connections Film to Person',
                'db_table': '"content"."person_film_work"',
                'ordering': ['role'],
                'unique_together': {('film_work', 'person', 'role')},
            },
        ),
        migrations.CreateModel(
            name='GenreFilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(db_column='film_work_id', on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('genre', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, related_name='films', to='movies.genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': '"content"."genre_film_work"',
                'ordering': ['genre__name'],
                'unique_together': {('film_work', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(through='movies.PersonFilmWork', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(through='movies.GenreFilmWork', to='movies.Genre'),
        ),
    ]
